# Generated by Django 5.0.1 on 2024-02-15 13:50

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('intitule', models.CharField(max_length=100)),
                ('option', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=7)),
                ('programme', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Suppleant',
            fields=[
                ('suppleant_nom', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('suppleant_prenom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('motif', models.TextField()),
                ('accord_suppleant', models.CharField(choices=[('Oui', ' Oui'), ('Non', ' Non'), ('En Cour', ' En Cour')], max_length=20)),
                ('inputation_salaire', models.CharField(choices=[('Mission Scientifique', 'Mission Scientifique'), ('Montée en charge nouvel académique', 'Montée en charge nouvel académique'), ('A titre gracieux', 'A titre gracieux'), ('Maladie de longue durée', 'Maladie de longue durée'), ("A déterminer par l'administration", "A déterminer par l'administration")], max_length=50)),
                ('cpo', models.IntegerField(blank=True, null=True)),
                ('remarque', models.TextField(blank=True)),
                ('salaire', models.FloatField(blank=True)),
                ('accord_cf', models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=10)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_cours', to='app.cours')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_utilisateur', to=settings.AUTH_USER_MODEL)),
                ('supleant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_suppleant', to='app.suppleant')),
            ],
        ),
    ]
