# Generated by Django 5.0.1 on 2024-02-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='accord_cf',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='demande',
            name='remarque',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demande',
            name='salaire',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
