# Generated by Django 5.0.1 on 2024-02-15 21:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_demande_accord_cf_alter_demande_remarque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
