# Generated by Django 5.0.1 on 2024-03-04 18:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='enseignants',
            field=models.ManyToManyField(blank=True, related_name='cours_enseignes', to=settings.AUTH_USER_MODEL),
        ),
    ]
